### PR TITLE
Changed 1st Heading on the page

### PR DESCRIPTION
**Pull request by huzaifa1-23**
Changed 1st Heading on the page blog-details-sidebar-right.html it was about augmented reality giving the link from where i got and adjusted https://www.sciencedirect.com/science/article/abs/pii/S0747563215303253

### CODE REVIEW

**Review by Remy-Reveltek — CHANGES_REQUESTED** [review]
If you look on original content character layout, there is only first word of the title is starting with Capital letter otherwise all are small. Please replace 1st capital letters of all words with small letters except first word of the line.

**Comment by huzaifa1-23** [comment]
Alright i am changing that

**Comment by huzaifa1-23** [comment]
As far as I know, In titles only prepositions  are written in lower
case letters. I followed that standard. But I will follow your instructions

Regards,

**Review by SuzyQuant — CHANGES_REQUESTED** [review]
Change the title to **AR Effects in Laboratories**

It's great you have a peer-reviewed journal you're referencing. However, be careful in using "Labs" because it's not a plural for laboratory.

**Comment by huzaifa1-23** [comment]
Alright

**Comment by misterhackney** [comment]
@Remy-Reveltek  - Suzanne is accurate on this.  Prepositions, conjunctions, and  Articles are the only 3 things we shouldn't capitalize.  Everything else gets a capitalization if it's in a title area, regardless if the original follows this rule.

**Pull request merged**
