### PR TITLE
Changed the paragraph under 1st heading

### PR DESCRIPTION
**Pull request by huzaifa1-23**

### CODE REVIEW

**Comment by Remy-Reveltek** [comment]
Please provide us with a proper title and description specifically where are you proposing changes. (This Edit) You made changes in the description of the first blog on OUR BLOG page.

**Comment by huzaifa1-23** [comment]
Ok I'll take care of it from now on

**Review by SuzyQuant — COMMENTED** [review]
Please attach proper procedure that you made when doing changes. Having a before and after photo would help and also the link as to where you did the changes.

Use Ctrl + Shift + S to snip a photo and attach here.

**Review by misterhackney — CHANGES_REQUESTED** [review]
Submit again so it fixes conflicts.

**Pull request closed without merging**
