### PR TITLE
updated the title

### PR DESCRIPTION
**Pull request by Zaryabayub**
updated the title under the field ocean science, blog #2

### CODE REVIEW

**Review by bjornmage — CHANGES_REQUESTED** [review]
Titles must have proper Capitalization.
Every single word except words that are:
Not Articles
Not Conjunctions
Not Prepositions

Need to be capitalized

**Comment by Zaryabayub** [comment]
Made changes as per the requirement

**Comment by bjornmage** [comment]
This either needs fixed again or canceled & redone. It is showing that there are conflicts with the branch.

**Comment by Zaryabayub** [comment]
I'm looking into it.

**Comment by Zaryabayub** [comment]
I hope its fixed now.

**Pull request closed without merging**
